apiVersion: v1
kind: Service
metadata:
  name: voting-be-lb
  labels:
    app: voting-be
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      nodePort: 30080   # NodePort as an external access point (optional if using LoadBalancer)
  selector:
    app: voting-be
